kind: pipeline
type: kubernetes
name: default

steps:
- name: docker  
  image: harbor.ntppool.org/ntppool/drone-kaniko:latest
  settings:
    dockerfile: base-os/Dockerfile
    context: base-os
    repo: perlorg/base-os
    registry: harbor.ntppool.org
    auto_tag: true
    tags: SHA7,${DRONE_SOURCE_BRANCH}
    cache: true
    username:
      from_secret: harbor_perlorg_username
    password:
      from_secret: harbor_perlorg_password
