when:
  - event: [push, pull_request, manual, tag]

steps:
  - name: generate-tags
    image: ghcr.io/abh/woodpecker-docker-tags-plugin:sha-86e52ce
    settings:
      tags: |
        branch
        sha
        edge -v latest
        raw -v build-${CI_PIPELINE_NUMBER}
        semver --format {{major}}
        semver --format {{major}}.{{minor}}
        semver --format {{major}}.{{minor}}.{{patch}}

  - name: docker
    image: woodpeckerci/plugin-kaniko
    when:
      - event: [push, tag, manual]
    settings:
      dockerfile: base-os/Dockerfile
      context: base-os
      registry: harbor.ntppool.org
      repo: perlorg/base-os
      cache: true
      username:
        from_secret: harbor_perlorg_username
      password:
        from_secret: harbor_perlorg_password
