when:
  - event: [push, pull_request, manual]

steps:
  - name: docker
    image: woodpeckerci/plugin-kaniko
    settings:
      dockerfile: base-os/Dockerfile
      context: base-os
      registry: harbor.ntppool.org
      repo: perlorg/base-os
      auto_tag: true
      tags:
        - ${CI_COMMIT_BRANCH}
        - ${CI_COMMIT_SHA:0:7}
      cache: true
      username:
        from_secret: harbor_perlorg_username
      password:
        from_secret: harbor_perlorg_password
